/**
 * generateAltPaths.js
 *
 * Generates alternative OSRM road-following paths for every route.
 * Alt paths are slight detours via parallel roads (stops offset by ~0.003°).
 * Output injected as route.alt_path (and alt_stops) into routes.js.
 *
 * Usage: node backend/scripts/generateAltPaths.js
 */

const fs = require('fs');
const path = require('path');
const https = require('https');

const ROUTES_FILE = path.resolve(__dirname, '../data/routes.js');
const OSRM_BASE = 'https://router.project-osrm.org/route/v1/driving/';

function delay(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

function httpsGet(url) {
  return new Promise((resolve, reject) => {
    https.get(url, (res) => {
      let data = '';
      res.on('data', chunk => { data += chunk; });
      res.on('end', () => {
        try { resolve(JSON.parse(data)); }
        catch(e) { reject(e); }
      });
    }).on('error', reject);
  });
}

/**
 * Offset a coordinate slightly to simulate a parallel road detour.
 * Alternates north/south offsets for each stop to create a realistic arc.
 */
function offsetStop(stop, idx) {
  // Use a wave pattern: even stops shift north-east, odd stops shift south-east
  const latOffset = (idx % 2 === 0) ? 0.004 : -0.003;
  const lngOffset = (idx % 3 === 0) ? 0.003 : 0.004;
  return {
    lat: parseFloat((stop.lat + latOffset).toFixed(6)),
    lng: parseFloat((stop.lng + lngOffset).toFixed(6))
  };
}

async function fetchOsrmPath(stops) {
  if (!stops || stops.length < 2) return null;
  
  // Build OSRM coordinate string: lng,lat;lng,lat;...
  const coords = stops.map(s => `${s.lng},${s.lat}`).join(';');
  const url = `${OSRM_BASE}${coords}?overview=full&geometries=geojson`;
  
  try {
    const data = await httpsGet(url);
    if (data.code !== 'Ok' || !data.routes || data.routes.length === 0) {
      console.warn(`  [WARN] OSRM returned no routes, using straight-line fallback`);
      return stops; // fallback
    }
    // Convert GeoJSON [lng, lat] -> {lat, lng}
    const coords = data.routes[0].geometry.coordinates;
    return coords.map(([lng, lat]) => ({
      lat: parseFloat(lat.toFixed(6)),
      lng: parseFloat(lng.toFixed(6))
    }));
  } catch (err) {
    console.error(`  [ERROR] OSRM fetch failed: ${err.message}`);
    return stops; // fallback to straight
  }
}

async function main() {
  console.log('[GenerateAltPaths] Loading routes.js...');
  
  // Read as text to preserve the file structure
  let fileContent = fs.readFileSync(ROUTES_FILE, 'utf8');
  
  // Extract routes by evaluating
  const tempFile = path.resolve(__dirname, '_temp_routes_eval.js');
  const evalContent = fileContent.replace('module.exports = routes;', 'module.exports = routes;');
  require(ROUTES_FILE); // ensure no syntax errors
  const routes = require(ROUTES_FILE);

  console.log(`[GenerateAltPaths] Processing ${routes.length} routes...\n`);

  const altPathData = {}; // routeId -> { alt_stops, alt_path }

  for (const route of routes) {
    console.log(`  Processing ${route.route_id}: ${route.name}`);
    
    // Create offset alt stops (close parallel road detour)
    const altStops = route.stops.map((stop, idx) => offsetStop(stop, idx));
    // Add start back at end for a closed loop
    altStops.push({ ...altStops[0] });
    
    console.log(`  Fetching OSRM alt path for ${route.route_id}...`);
    const altPath = await fetchOsrmPath(altStops);
    
    altPathData[route.route_id] = {
      alt_stops: altStops.slice(0, -1), // remove appended first for clean stops
      alt_path: altPath
    };
    
    console.log(`  ✓ ${route.route_id}: alt_path has ${altPath ? altPath.length : '0'} points\n`);
    await delay(1300); // Rate limit OSRM public API
  }

  // Now write the data as a separate file that routes.js can reference
  const outFile = path.resolve(__dirname, '../data/altPaths.js');
  
  const jsContent = `// Auto-generated by generateAltPaths.js
// Alternative road paths for each route (used when a route is blocked).
const altPaths = ${JSON.stringify(altPathData, null, 2)};
module.exports = altPaths;
`;

  fs.writeFileSync(outFile, jsContent, 'utf8');
  console.log(`\n[GenerateAltPaths] Wrote alt paths to backend/data/altPaths.js`);
  console.log(`[GenerateAltPaths] Done! ${Object.keys(altPathData).length} routes updated.`);
}

main().catch(err => {
  console.error('[GenerateAltPaths] Fatal error:', err);
  process.exit(1);
});
